# Generated by Django 2.1.3 on 2019-01-13 12:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_categorymapping_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='categorymapping',
            unique_together={('category', 'user')},
        ),
    ]
