# Generated by Django 2.1.3 on 2019-01-22 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_region'),
        ('question', '0003_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='limit',
            field=models.IntegerField(default=1800),
        ),
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Region'),
        ),
    ]
